version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/""
    schedule:
      interval: "daily"
    reviewers:
      - "ChristopheLav"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ChristopheLav"