name: Build and Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        name: Set Node.js 16.x
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint

  test:
    needs: build
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create a test deployment annotation
        uses: ./
        with:
          app-id: ${{ secrets.APPINSIGHTS_APP_ID }}
          api-key: ${{ secrets.APPINSIGHTS_API_KEY }}
          name: Test Deployment (${{ matrix.runs-on }})