name: Licensed

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'imgs\*'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs\*'

permissions:
  contents: read  # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v6
      
      - run: npm ci --ignore-scripts

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.5

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - run: npm run licensed-install

      - run: npm run licensed-check