name: Licensed

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'imgs\*'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs\*'

permissions:
  contents: read  # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v6
      
      - run: npm ci --ignore-scripts

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.x

      - name: Install licensed tool
        run: |
          cd "$RUNNER_TEMP"
          curl -Lfs -o licensed.tar.gz https://github.com/licensee/licensed/archive/refs/tags/v5.1.0.tar.gz
          tar -xzf licensed.tar.gz
          cd licensed-5.1.0
          bundle install

      - name: Check cached dependency records
        run: |
          cd ${{ github.workspace }}
          BUNDLE_GEMFILE=$RUNNER_TEMP/licensed-5.1.0/Gemfile bundle exec $RUNNER_TEMP/licensed-5.1.0/exe/licensed status