name: Licensed

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'imgs\*'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs\*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run licensed-check