name: Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Checks"]
    types: 
      - completed

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          

      - name: Create a test deployment annotation
        uses: ./
        with:
          app-id: ${{ secrets.APPINSIGHTS_APP_ID }}
          api-key: ${{ secrets.APPINSIGHTS_API_KEY }}
          name: Test Deployment (${{ matrix.runs-on }})