name: Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Checks"]
    types: 
      - completed

permissions:
  id-token: write # This is required for requesting the JWT (azure login with OIDC)
  contents: read  # This is required for actions/checkout

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}
    environment:
      name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Create a test deployment annotation (failed state)
        uses: ./
        with:
          app-id: ${{ secrets.APPINSIGHTS_APP_ID }}
          is-deployment-succeed: false
          name: Test Deployment (${{ matrix.runs-on }})
          
      - name: Create a test deployment annotation (success state)
        uses: ./
        with:
          app-id: ${{ secrets.APPINSIGHTS_APP_ID }}
          is-deployment-succeed: true
          name: Test Deployment (${{ matrix.runs-on }})